---
language: bash
before_install:
  - sudo add-apt-repository -y ppa:kelleyk/emacs # Emacs 25
  - sudo apt-get update
  - sudo apt-get install -y emacs25
script:
  - bin/fetch-configlet
  - bin/configlet lint .
  - bin/test-examples
