---
language: bash
before_install:
  - sudo add-apt-repository -y ppa:cassou/emacs # Emacs 24.3
  - sudo apt-get update
  - sudo apt-get install -y emacs24-nox
script:
  - bin/fetch-configlet
  - bin/configlet .
  - bin/test-examples
