name: emacs-lisp / main

on:
  push:
    branches: [master, main]
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: purcell/setup-emacs@ddbe7a402671fcbad2a5e1a0f503d61dd95a0b7c
        with:
          version: 28.1

      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Run exercism/emacs-lisp ci (runs tests) for all exercises
        run: |
          bash bin/stub-check
          bash bin/test-examples
